DROP TABLE IF EXISTS bookmarks;

CREATE TABLE bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  page_url TEXT NOT NULL,
  page_description TEXT,
  rating INTEGER 
);